/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    payments: Payment;
    media: Media;
    subscriptions: Subscription;
    attendance: Attendance;
    'training-classes': TrainingClass;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    attendance: AttendanceSelect<false> | AttendanceSelect<true>;
    'training-classes': TrainingClassesSelect<false> | TrainingClassesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    schedule: Schedule;
  };
  globalsSelect: {
    schedule: ScheduleSelect<false> | ScheduleSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Użytkownicy systemu - członkowie, trenerzy i administratorzy
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Imię członka/trenera
   */
  firstName: string;
  /**
   * Nazwisko członka/trenera
   */
  lastName: string;
  /**
   * Pełne imię i nazwisko (generowane automatycznie)
   */
  fullName?: string | null;
  /**
   * Numer telefonu
   */
  phone: string;
  /**
   * Data urodzenia
   */
  dateOfBirth?: string | null;
  /**
   * Zdjęcie profilowe (opcjonalne, głównie dla trenerów)
   */
  profileImage?: (number | null) | Media;
  /**
   * Pseudonim (opcjonalne, głównie dla trenerów)
   */
  nickname?: string | null;
  /**
   * Opis trenera (opcjonalne, wyświetlane na stronie)
   */
  description?: string | null;
  /**
   * Rola użytkownika w systemie
   */
  role: 'member' | 'trainer' | 'admin';
  /**
   * Status karnetu (aktualizowany automatycznie)
   */
  subscriptionStatus?: ('active' | 'inactive') | null;
  /**
   * Notatki o członku
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Płatności za karnety
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  /**
   * Członek, który dokonał płatności
   */
  member: number | User;
  /**
   * Kwota płatności (domyślnie 230 zł)
   */
  amount: number;
  /**
   * Metoda płatności
   */
  paymentMethod: 'cash' | 'transfer';
  /**
   * Data płatności
   */
  paymentDate: string;
  /**
   * Termin płatności (automatycznie ustawiany na 10. dzień miesiąca)
   */
  dueDate: string;
  /**
   * Status płatności
   */
  status: 'completed' | 'pending' | 'cancelled';
  /**
   * Notatki dotyczące płatności
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Karnety członkowskie - ważność członkostwa
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  /**
   * Członek posiadający karnet
   */
  member: number | User;
  /**
   * Płatność powiązana z tym karnetem
   */
  payment: number | Payment;
  /**
   * Data rozpoczęcia karnetu
   */
  startDate: string;
  /**
   * Data zakończenia karnetu (10. dzień kolejnego miesiąca)
   */
  endDate: string;
  /**
   * Status karnetu
   */
  status: 'active' | 'inactive';
  /**
   * Automatyczne odnowienie karnetu
   */
  autoRenew?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lista obecności na treningach
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance".
 */
export interface Attendance {
  id: number;
  trainingClass: number | TrainingClass;
  /**
   * Data i godzina treningu
   */
  trainingDate: string;
  /**
   * Trener prowadzący trening
   */
  trainer: number | User;
  /**
   * Lista członków obecnych na treningu
   */
  attendees?: (number | User)[] | null;
  /**
   * Notatki dotyczące treningu
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Rodzaje treningów dostępnych w klubie
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-classes".
 */
export interface TrainingClass {
  id: number;
  /**
   * Nazwa rodzaju zajęć (np. MMA, BJJ, Muay Thai)
   */
  name: string;
  /**
   * Poziom zaawansowania dla tego rodzaju zajęć
   */
  level: 'beginner' | 'intermediate' | 'advanced' | 'kids';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'attendance';
        value: number | Attendance;
      } | null)
    | ({
        relationTo: 'training-classes';
        value: number | TrainingClass;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  fullName?: T;
  phone?: T;
  dateOfBirth?: T;
  profileImage?: T;
  nickname?: T;
  description?: T;
  role?: T;
  subscriptionStatus?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  member?: T;
  amount?: T;
  paymentMethod?: T;
  paymentDate?: T;
  dueDate?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  member?: T;
  payment?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  autoRenew?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance_select".
 */
export interface AttendanceSelect<T extends boolean = true> {
  trainingClass?: T;
  trainingDate?: T;
  trainer?: T;
  attendees?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-classes_select".
 */
export interface TrainingClassesSelect<T extends boolean = true> {
  name?: T;
  level?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Tygodniowy harmonogram zajęć w klubie Bonzai MMA
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule".
 */
export interface Schedule {
  id: number;
  /**
   * Harmonogram zajęć dla każdego dnia tygodnia
   */
  days: {
    /**
     * Wybierz dzień tygodnia
     */
    name: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
    /**
     * Lista zajęć w danym dniu
     */
    classes?:
      | {
          /**
           * Godzina rozpoczęcia zajęć (format: HH:MM, np. 18:00)
           */
          startTime: string;
          /**
           * Godzina zakończenia zajęć (format: HH:MM, np. 19:30)
           */
          endTime: string;
          /**
           * Wybierz rodzaj zajęć
           */
          trainingClass: number | TrainingClass;
          /**
           * Trener prowadzący zajęcia
           */
          trainer?: (number | null) | User;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule_select".
 */
export interface ScheduleSelect<T extends boolean = true> {
  days?:
    | T
    | {
        name?: T;
        classes?:
          | T
          | {
              startTime?: T;
              endTime?: T;
              trainingClass?: T;
              trainer?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}